package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.BuildStep
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.powerShell
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'HelloWorld'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("HelloWorld")) {
    check(name == "Hello world") {
        "Unexpected name: '$name'"
    }
    name = "step-01"

    expectSteps {
        step {
            name = "Restore Nuget Packages"
            type = "jb.nuget.installer"
            param("nuget.path", "%teamcity.tool.NuGet.CommandLine.DEFAULT%")
            param("nuget.updatePackages.mode", "sln")
            param("sln.path", "%SolutionPath%")
        }
    }
    steps {
        update<BuildStep>(0) {
            name = "Step01"
        }
        insert(1) {
            powerShell {
                name = "Step02"
                scriptMode = script {
                    content = "Get-ChildItem"
                }
            }
        }
    }
}
